# Generated by Django 5.1.5 on 2025-02-08 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt_balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt_balance', models.DecimalField(decimal_places=8, max_digits=18)),
                ('coin_balance', models.DecimalField(decimal_places=8, max_digits=18)),
                ('total_balance', models.DecimalField(decimal_places=8, max_digits=18)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('total_buy_amount', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('total_buy_value', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('total_sell_value', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('average_buy_price', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('is_closed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to=settings.AUTH_USER_MODEL)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='portfolio.coin')),
            ],
            options={
                'unique_together': {('user', 'coin')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('value', models.DecimalField(decimal_places=8, max_digits=18)),
                ('profit_loss_value', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('profit_loss_percentage', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.box')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
