# Generated by Django 5.1.5 on 2025-02-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='average_sell_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='box',
            name='total_sell_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
