# Generated by Django 5.1.5 on 2025-02-13 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_box_average_sell_price_box_total_sell_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 13, 7, 9, 6, 358832, tzinfo=datetime.timezone.utc)),
        ),
    ]
