# Generated by Django 5.1.5 on 2025-02-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='box',
            unique_together=set(),
        ),
    ]
