# Generated by Django 5.1.5 on 2025-02-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_box_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=0.02, max_digits=18),
        ),
    ]
