# Generated by Django 5.1.5 on 2025-03-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_transaction_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='icon_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
